### PR TITLE
Fixes #1694: Additional fix. Capture the first left-most x-forwarded-…

### LINKED ISSUE #1694: Capture the source port in the http2 adaptor
The source port can be found in the `x-forwarded-for` header. Capture the value of this header in the vanflow attribute `VFLOW_ATTRIBUTE_SOURCE_HOST`

### PR DESCRIPTION
**Pull request by ganeshmurthy**
…for header value

### CODE REVIEW

File: src/observers/http2/http2_observer.c [hunk 1]
```diff
@@ -246,7 +240,33 @@ static int on_header_recv_callback(qd_http2_decoder_connection_t *conn_state,
...
+                // X-Forwarded-For: 2001:db8:85a3:8d3:1319:8a2e:370:7348, 197.1.773.201
+                // X-Forwarded-For: 195.0.223.001
+                // X-Forwarded-For: 203.0.113.195, 2007:db5:85a3:8d3:1319:8a2e:370:3221
+                //
+                // We will obtain the value of the first X-Forwarded-For (2001:db8:85a3:8d3:1319:8a2e:370:7348, 197.1.773.201) and ignore the
+                // other two X-Forwarded-For headers.
+                // The first X-Forwarded-For header is comma separated list, we will obtain the leftmost (the first) value (2001:db8:85a3:8d3:1319:8a2e:370:7348) in the list
+
+                // const uint8_t *value passed into this function is guaranteed to be NULL-terminated
+                char value_copy[valuelen+1];
```
Comment (kgiusti) [inline src/observers/http2/http2_observer.c:262]: Is there a limit to valuelen?  Can it be large enough to overflow the stack?

Comment (ganeshmurthy) [reply src/observers/http2/http2_observer.c]: > so hardcoding a array size of 128 would be more than enough I would think.

Agreed. I made the change. Thanks @kgiusti
