### PR TITLE
Fixes #376 - Address watch doesn't work on edge routers

### LINKED ISSUE #376: Address watch doesn't work on Edge routers
Address watches established on edge routers do not detect reachability in other parts of the network.  The tests don't address these cases.

### PR DESCRIPTION
**Pull request by ted-ross**

### CODE REVIEW

File: src/router_core/address_watch.c [hunk 1]
```diff
@@ -127,15 +129,43 @@ static void qdr_core_watch_address_CT(qdr_core_t *core, qdr_action_t *action, bo
...
+                watch->watch_handle = action->args.io.value32_1;
+                watch->addr         = addr;
+                watch->handler      = action->args.io.watch_handler;
+                watch->context      = action->args.io.context;
+                DEQ_INSERT_TAIL(core->addr_watches, watch);
+
+                addr->watch = watch;
+                addr->ref_count++;
+
+                qdrc_event_addr_raise(core, QDRC_EVENT_ADDR_WATCH_ON, addr);
```
Comment (kgiusti) [inline src/router_core/address_watch.c:164]: Would it be possible to trigger the newly watched address now so the watcher gets the current counters?

Comment (ted-ross) [reply src/router_core/address_watch.c:164]: This sounds like a good idea.

Comment (ted-ross) [reply src/router_core/address_watch.c:167]: I added the requested feature.

**Review by kgiusti — APPROVED** [review]
