### PR TITLE
Fixes #1793: Move the LINK vflow record from the connector object to …

### LINKED ISSUE #1793: VFLOW_RECORD_LINK Lifecycle Bug
With the introduction of ordinals and certificate rotation, the LINK records now behave differently. I expect one LINK record for the lifetime of the configured router connector, but instead I am seeing multiples.

When an sslProfile associated with a connector is updated with a new ordinal I am observing a new LINK record, and when that sslProfile is updated with an oldestValidOrdinal excluding an active connection I observe the terminal event for the previous LINK record.

I only expect one LINK record per connector.

Example logs from the network-observer (with -vanflow-logging-profile=all set)

To begin, a Link is running and healthy. It has the vanflow ID `s6tsm:7`. Periodically, the router publishes updates to the octets sent/received.
```
2025/06/02 20:45:01 INFO flow/v1/LinkRecord component=vanflow record.Octets=101433 record.OctetsReverse=137724 record.ID=s6tsm:7 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:02 INFO flow/v1/LinkRecord component=vanflow record.OctetsReverse=138358 record.ID=s6tsm:7 record.Octets=101895 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:03 INFO flow/v1/LinkRecord component=vanflow record.Octets=102311 record.ID=s6tsm:7 record.OctetsReverse=138891 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:04 INFO flow/v1/LinkRecord component=vanflow record.Octets=102773 record.OctetsReverse=139525 record.ID=s6tsm:7 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:05 INFO flow/v1/LinkRecord component=vanflow record.Octets=103189 record.OctetsReverse=140058 record.ID=s6tsm:7 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:06 INFO flow/v1/LinkRecord component=vanflow record.ID=s6tsm:7 record.Octets=103651 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
```

The control plane bumps the associated sslProfile ordinal, and the router unexpectedly adds a NEW LinkRecord with ID `s6tsm:8`, which takes over as the active - and gets subsequent updates for octets.
```
2025/06/02 20:45:06 INFO flow/v1/LinkRecord component=vanflow record.DestHost=172.18.255.129 record.Octets=0 record.OctetsReverse=833 record.DownCount=0 record.LastUp=1.748897106616349e+15 record.StartTime=2025-06-02T20:45:06.602471Z record.Name=link-east record.LinkCost=1 record.Parent=s6tsm:0 record.Peer=7lpx7:1 record.Role=inter-router record.Protocol=amqp record.DestPort=55671 record.ID=s6tsm:8 record.Status=up message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:07 INFO flow/v1/LinkRecord component=vanflow record.Octets=567 record.OctetsReverse=1366 record.ID=s6tsm:8 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:08 INFO flow/v1/LinkRecord component=vanflow record.Octets=1029 record.OctetsReverse=2000 record.ID=s6tsm:8 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:09 INFO flow/v1/LinkRecord component=vanflow record.Octets=1587 record.ID=s6tsm:8 record.OctetsReverse=2785 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:10 INFO flow/v1/LinkRecord component=vanflow record.ID=s6tsm:8 record.OctetsReverse=3761 record.Octets=2270 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
2025/06/02 20:45:11 INFO flow/v1/LinkRecord component=vanflow record.OctetsReverse=4294 record.Octets=2686 record.ID=s6tsm:8 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
...
```

The control plane bumps the associated sslProfile oldestValidOrdinal to match the configured ordinal. The router closes the old connections and sends a terminal event for the `s6tsm:7` Link.
```
2025/06/02 20:45:26 INFO flow/v1/LinkRecord component=vanflow record.DownCount=1 record.Result=unknown record.ID=s6tsm:7 record.EndTime=2025-06-02T20:45:26.071745Z record.Status=down record.Reason="" record.LastDown=1.748897126071744e+15 message.to=mc/sfe.s6tsm:0 message.subject=RECORD
```

### PR DESCRIPTION
**Pull request by ganeshmurthy**
…connector_config object. This ensures

that only one LINK record exists per logical link

### CODE REVIEW

File: src/adaptors/amqp/qd_connector.c [hunk 1]
```diff
@@ -504,11 +485,14 @@ void qd_connector_remove_connection(qd_connector_t *connector, bool final, const
     qd_connection_t *ctx = connector->qd_conn;
     if (!connector->is_data_connector && !connector->oper_status_down  && !final) {
         connector->oper_status_down = true;
-        vflow_set_string(connector->vflow_record, VFLOW_ATTRIBUTE_OPER_STATUS, "down");
-        vflow_inc_counter(connector->vflow_record, VFLOW_ATTRIBUTE_DOWN_COUNT, 1);
-        vflow_set_timestamp_now(connector->vflow_record, VFLOW_ATTRIBUTE_DOWN_TIMESTAMP);
-        vflow_set_string(connector->vflow_record, VFLOW_ATTRIBUTE_RESULT, condition_name        ? condition_name : "unknown");
-        vflow_set_string(connector->vflow_record, VFLOW_ATTRIBUTE_REASON, condition_description ? condition_description : "");
+        qd_connector_config_t *ctor_config = connector->ctor_config;
```
Comment (ted-ross) [inline src/adaptors/amqp/qd_connector.c:488]: Is it possible that the loss of the "old" control connection might be registered here and set the OPER_STATUS to "down" even though the "new" control connection is up?

Comment (ganeshmurthy) [reply src/adaptors/amqp/qd_connector.c:488]: BTW, I am writing a test for this as well.

Comment (ted-ross) [reply src/adaptors/amqp/qd_connector.c:488]: This seems like a clever solution.  The only question I have is whether this breaks when the link doesn't use TLS (i.e. there's no SslProfile).  However, I don't think a connector would ever be rotated if there wasn't an SslProfile, so this is probably fine.

File: src/adaptors/amqp/qd_connector.c [hunk 2]
```diff
@@ -473,21 +451,27 @@ void qd_connector_remote_opened(qd_connector_t *connector)
...
 {
-    assert(ctx->connector == 0);
-
+    assert(qd_conn->connector == 0);
     sys_atomic_inc(&connector->ref_count);
-    ctx->connector = connector;
-    connector->qd_conn = ctx;
+    qd_conn->connector = connector;
+    connector->qd_conn = qd_conn;
+    if (!connector->is_data_connector) {
```
Comment (mgoulish) [inline src/adaptors/amqp/qd_connector.c:460]: What does this mean that it is not a data connector?  Could we have a comment to explain?

Comment (mgoulish) [inline src/adaptors/amqp/qd_connector.c:460]: What does this mean that it is not a data connector? Could we have a comment to explain?

Comment (mgoulish) [reply src/adaptors/amqp/qd_connector.c:460]: Oh, I see. It means that it's a control connector.

Never mind.

**Review by mgoulish — COMMENTED** [review]
OK!  Everything looks reasonable and straightforward  -- I don't yet understand why this fixes the bug, but maybe I can get you to explain later.

Looks good!
