### PR TITLE
Fixes #925: add Containerfile test that runs `skstat -l`

### LINKED ISSUE #925: Test for the Containerfile does not attempt to use skstat/skmanage, misses issues with Proton Python install
```
$ docker run --name router -itd --rm quay.io/skupper/skupper-router:main
196e2784d48f4e597cf0057e9daca88d6a88c375d75f62fb98959e935308b6db
$ docker exec router skstat -l
Traceback (most recent call last):
  File "/usr/bin/skstat", line 29, in <module>
    from skupper_router.management.client import Node
  File "/usr/lib/python3.9/site-packages/skupper_router/management/client.py", line 22, in <module>
    import proton
ModuleNotFoundError: No module named 'proton'
```

Reported by @fgiorgetti

### PR DESCRIPTION
**Pull request by jiridanek**

### CODE REVIEW

File: tests/testcontainers/test_h2spec.rs [hunk 1]
```diff
@@ -225,8 +288,69 @@ async fn test_h2spec() {
...
+}
+
+impl LogPrinter {
+    fn new() -> Self {
+        Self {
+            tasks: vec![],
+        }
+    }
+
+    fn print(&mut self, log_stream: Fuse<(impl Stream<Item=String> + Unpin + Sized + Send + 'static)>) {
```
Comment (jiridanek) [inline tests/testcontainers/test_h2spec.rs:311]: yes, the type signature is kind of crazy, and even IDE plugin has some trouble with it, turns out

* https://github.com/intellij-rust/intellij-rust/issues/10363

**Comment by ganeshmurthy** [comment]
I am not knowledgeable in Rust. If the skstat -l command fails for some reason, do you think the container build should fail as well ?
Besides that, feel free to commit.

**Review by ganeshmurthy — APPROVED** [review]

**Comment by jiridanek** [comment]
> I am not knowledgeable in Rust.

Me neither. When you see me type Rust, it is just the last tutorial I gulped trying to get out, all this mediated through IntelliSense and IDE auto fixes.

And writing code is actually easier than reading it, in some cases.

> If the skstat -l command fails for some reason, do you think the container build should fail as well ?

I guess. If the image is going to be broken, better  not push it. That should be a good enhancement, yes.

* https://github.com/skupperproject/skupper-router/issues/1063
