### PR TITLE
Fixed #269, #230: Added a lock around proton connection creation and …

### LINKED ISSUE #269: [c-benchmarks] AddressSanitizer: use-after-poison in qdr_tcp_connection_ingress
https://github.com/skupperproject/skupper-router/runs/5789567654?check_suite_focus=true#step:9:2791

This is supposed to be fixed by https://github.com/skupperproject/skupper-router/issues/228 and should not be present anymore. Maybe the test is doing something wrong?

```
64: ==3639==ERROR: AddressSanitizer: use-after-poison on address 0x6190002d3d68 at pc 0x56015a58c633 bp 0x7f4c82e3ddd0 sp 0x7f4c82e3ddc0
64: READ of size 8 at 0x6190002d3d68 thread T29
64:     #0 0x56015a58c632 in qdr_tcp_connection_ingress ../src/adaptors/tcp_adaptor.c:979
64:     #1 0x56015a590bc3 in handle_listener_event ../src/adaptors/tcp_adaptor.c:1221
64:     #2 0x56015a7a046c in handle_event_with_context ../src/server.c:780
64:     #3 0x56015a7a04f3 in do_handle_listener ../src/server.c:791
64:     #4 0x56015a7a30e2 in handle ../src/server.c:986
64:     #5 0x56015a7a4d64 in thread_run ../src/server.c:1095
64:     #6 0x56015a655e63 in _thread_init ../src/posix/threading.c:172
64:     #7 0x7f4c90a99608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
64:     #8 0x7f4c8f547162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)
64: 
64: 0x6190002d3d68 is located 232 bytes inside of 960-byte region [0x6190002d3c80,0x6190002d4040)
64: allocated by thread T29 here:
64:     #0 0x7f4c90c0faa5 in posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0x10eaa5)
64:     #1 0x56015a5a7828 in qd_alloc ../src/alloc_pool.c:396
64:     #2 0x56015a57cabc in new_qdr_tcp_connection_t ../src/adaptors/tcp_adaptor.c:125
64:     #3 0x56015a58b68b in qdr_tcp_connection_ingress ../src/adaptors/tcp_adaptor.c:950
64:     #4 0x56015a590bc3 in handle_listener_event ../src/adaptors/tcp_adaptor.c:1221
64:     #5 0x56015a7a046c in handle_event_with_context ../src/server.c:780
64:     #6 0x56015a7a04f3 in do_handle_listener ../src/server.c:791
64:     #7 0x56015a7a30e2 in handle ../src/server.c:986
64:     #8 0x56015a7a4d64 in thread_run ../src/server.c:1095
64:     #9 0x56015a655e63 in _thread_init ../src/posix/threading.c:172
64:     #10 0x7f4c90a99608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
64: 
64: Thread T29 created by T26 here:
64:     #0 0x7f4c90b3b805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
64:     #1 0x56015a655fd2 in sys_thread ../src/posix/threading.c:181
64:     #2 0x56015a7ac7ac in qd_server_run ../src/server.c:1489
64:     #3 0x56015a81cdd0 in QDR::run() const ../tests/c_benchmarks/../c_unittests/helpers.hpp:238
64:     #4 0x56015a820758 in DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}::operator()() const ../tests/c_benchmarks/bm_tcp_adapter.cpp:240
64:     #5 0x56015a828716 in void std::__invoke_impl<void, DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>(std::__invoke_other, DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
64:     #6 0x56015a828393 in std::__invoke_result<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>::type std::__invoke<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>(std::__invoke_result&&, (DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}&&)...) /usr/include/c++/9/bits/invoke.h:95
64:     #7 0x56015a828125 in void std::thread::_Invoker<std::tuple<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
64:     #8 0x56015a827f02 in std::thread::_Invoker<std::tuple<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
64:     #9 0x56015a827da8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
64:     #10 0x7f4c9007ade3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
64: 
64: Thread T26 created by T0 here:
64:     #0 0x7f4c90b3b805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
64:     #1 0x7f4c9007b0a8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd70a8)
64:     #2 0x56015a820ae3 in DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../tests/c_benchmarks/bm_tcp_adapter.cpp:235
58: 2022-04-01 14:33:18.737776 TCP_TEST test_01_tcp_EC1_INTB Client test_01_tcp_EC1_INTB_0_1_1 exited normally
58: 2022-04-01 14:33:18.738091 TCP_TEST test_01_tcp_EC1_INTB SUCCESS
58: 2022-04-01 14:33:18.738342 TCP_TEST test_01_tcp_basic_connectivity Stop test_01_tcp_EC1_INTB SUCCESS
58: 2022-04-01 14:33:18.738450 TCP_TEST test_01_tcp_basic_connectivity Start test_01_tcp_EC1_INTC
58: 2022-04-01 14:33:18.738564 TCP_TEST test_01_tcp_EC1_INTC Start do_tcp_echo_n_routers
58: 2022-04-01 14:33:18.738668 TCP_TEST test_01_tcp_EC1_INTC Running pair 0 EC1->INTC size=1 count=1
64:     #3 0x56015a81a4d1 in BM_TCPEchoServerLatency1QDRThread ../tests/c_benchmarks/bm_tcp_adapter.cpp:298
64:     #4 0x7f4c90aed72e in benchmark::internal::BenchmarkInstance::Run(unsigned long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*) const (/lib/x86_64-linux-gnu/libbenchmark.so.1+0x3972e)
64: 
64: SUMMARY: AddressSanitizer: use-after-poison ../src/adaptors/tcp_adaptor.c:979 in qdr_tcp_connection_ingress
64: Shadow bytes around the buggy address:
64:   0x0c3280052750: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c3280052760: f7 f7 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
64:   0x0c3280052770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
64:   0x0c328005[2780](https://github.com/skupperproject/skupper-router/runs/5789567654?check_suite_focus=true#step:9:2780): fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
64:   0x0c328005[2790](https://github.com/skupperproject/skupper-router/runs/5789567654?check_suite_focus=true#step:9:2790): 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
64: =>0x0c3[2800](https://github.com/skupperproject/skupper-router/runs/5789567654?check_suite_focus=true#step:9:2800)527a0: 00 00 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7[f7]f7 f7
64:   0x0c32800527b0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c32800527c0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c32800527d0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c32800527e0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c32800527f0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64: Shadow byte legend (one shadow byte represents 8 application bytes):
64:   Addressable:           00
64:   Partially addressable: 01 02 03 04 05 06 07 
64:   Heap left redzone:       fa
64:   Freed heap region:       fd
64:   Stack left redzone:      f1
64:   Stack mid redzone:       f2
64:   Stack right redzone:     f3
64:   Stack after return:      f5
64:   Stack use after scope:   f8
64:   Global redzone:          f9
64:   Global init order:       f6
64:   Poisoned by user:        f7
64:   Container overflow:      fc
64:   Array cookie:            ac
64:   Intra object redzone:    bb
64:   ASan internal:           fe
64:   Left alloca redzone:     ca
64:   Right alloca redzone:    cb
64:   Shadow gap:              cc
64: ==3639==ABORTING
```

### PR DESCRIPTION
**Pull request by ganeshmurthy**
…acceptance code so the PN_RAW_CONNECTION_DISCONNECTED event does not free the connection and its context from underneath

### CODE REVIEW

File: src/adaptors/tcp_adaptor.c [hunk 1]
```diff
@@ -982,13 +982,20 @@ static qdr_tcp_connection_t *qdr_tcp_connection_ingress(qd_tcp_listener_t* liste
     tc->bridge->connections_opened +=1;
     UNLOCK(tc->bridge->stats_lock);
 
+    LOCK(tc->activation_lock);
```
Comment (kgiusti) [inline src/adaptors/tcp_adaptor.c:985]: Can you move this further down in the code?  Like right before calling pn_listener_raw_accept?  There's no need to lock at this point, and by calling it here we now nest locks with the log lock, which we really don't want to do.

File: src/adaptors/tcp_adaptor.c [hunk 2]
```diff
@@ -1132,18 +1140,24 @@ static qdr_tcp_connection_t *qdr_tcp_connection_egress(qd_tcp_connector_t *conne
         qd_log(tcp_adaptor->log_source, QD_LOG_INFO,
                "[C%"PRIu64"] call pn_proactor_raw_connect(). Egress connecting to: %s",
                tc->conn_id, tc->bridge->host_port);
+
+        LOCK(tc->activation_lock);
```
Comment (kgiusti) [inline src/adaptors/tcp_adaptor.c:1144]: same here: although no log call, pn_raw_connection() does a lot of work as well - stuff like allocating memory. In general we should try to minimize the duration of holding a lock to only the exact critical region.

**Review by kgiusti — CHANGES_REQUESTED** [review]

File: src/adaptors/tcp_adaptor.c [hunk 3]
```diff
@@ -982,13 +982,20 @@ static qdr_tcp_connection_t *qdr_tcp_connection_ingress(qd_tcp_listener_t* liste
...
     UNLOCK(tc->bridge->stats_lock);
 
+    LOCK(tc->activation_lock);
     tc->pn_raw_conn = pn_raw_connection();
     pn_raw_connection_set_context(tc->pn_raw_conn, tc);
     //the following call will cause a PN_RAW_CONNECTION_CONNECTED
     //event on another thread, which is where the rest of the
     //initialisation will happen, through a call to
     //qdr_tcp_connection_ingress_accept
     qd_log(tcp_adaptor->log_source, QD_LOG_INFO, "[C%"PRIu64"] call pn_listener_raw_accept()", tc->conn_id);
```
Comment (ted-ross) [inline src/adaptors/tcp_adaptor.c:992]: Should this _really_ be an INFO level log?  Seems more lie a DEBUG log to me.  Ditto below...

**Review by ted-ross — APPROVED** [review]

File: src/adaptors/tcp_adaptor.c [hunk 4]
```diff
@@ -984,21 +997,24 @@ static qdr_tcp_connection_t *qdr_tcp_connection_ingress(qd_tcp_listener_t* liste
...
+    // thread. IF you want to access tc after this call, the activation_lock  must be held to prevent the code in PN_RAW_CONNECTION_DISCONNECTED handler from running
+    // and freeing this connection(qdr_tcp_connection_t) from underneath. The PN_RAW_CONNECTION_DISCONNECTED event might occur if the
+    // client that initiated the connection, closes the connection while we are trying to accept the connection.
+    // For example:
+    //     LOCK(tc->activation_lock);
+    //     pn_listener_raw_accept(listener->pn_listener, tc->pn_raw_conn);
+    //     call_some_function(tc->conn_id);   // if the activation_lock is not held, tc might be freed
+    //     UNLOCK(tc->activation_lock);
+    pn_listener_raw_accept(listener->pn_listener, tc->pn_raw_conn);
     return tc;
```
Comment (kgiusti) [inline src/adaptors/tcp_adaptor.c:1018]: Not part of this PR - but probably deserves a separate issue: given the comment (which is great btw) then it is not safe to return tc to the caller, since the memory pointed to by tc can now be invalid (freed via another thread handling PR_RAW_CONNECTION_DISCONNECTED asynchronously).

**Review by kgiusti — APPROVED** [review]
This LGTM but let's get @ted-ross to verify that the changes to the plog order are valid.  And I'd like to see a clean CI run before merging - IIUC these CI failures may be due to an instability introduced on proton main and probably have nothing to do with this patch but let's play it safe.

So this patch gets my approval once the above have been taken into consideration.

File: src/adaptors/tcp_adaptor.c (hunk 4 above)
Comment (ganeshmurthy) [reply src/adaptors/tcp_adaptor.c:1018]: I added a bit of code to clarify the return values. Please take a look. I also renamed dispatcher to dispatcher_conn

**Review by ted-ross — APPROVED** [review]
