### PR TITLE
Fixes #391: properly set delivery outcome on connection close

### LINKED ISSUE #391: test_70_half_closed failing in system_tests_tcp_adaptor
```
 =================================== FAILURES ===================================
________________________ TcpAdaptor.test_70_half_closed ________________________

self = <tests.system_tests_tcp_adaptor.TcpAdaptor testMethod=test_70_half_closed>

    def test_70_half_closed(self):
        if DISABLE_SELECTOR_TESTS:
            self.skipTest(DISABLE_SELECTOR_REASON)
        if not ncat_available():
            self.skipTest("Ncat utility is not available")
        name = "test_70_half_closed"
        self.logger.log("TCP_TEST Start %s" % name)
        self.ncat_runner(name, "INTA", "INTA", self.logger)
        self.ncat_runner(name, "INTA", "INTB", self.logger)
>       self.ncat_runner(name, "INTA", "INTC", self.logger)

/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_tcp_adaptor.py:947: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.system_tests_tcp_adaptor.TcpAdaptor testMethod=test_70_half_closed>
tname = 'test_70_half_closed', client = 'INTA', server = 'INTC'
logger = <system_test.Logger object at 0x7fd8632e5e40>

    def ncat_runner(self, tname, client, server, logger):
        name = "%s_%s_%s" % (tname, client, server)
        logger.log(name + " Start")
        out = self.run_ncat(TcpAdaptor.tcp_client_listener_ports[client][server], logger, data=b'abcd')
        logger.log("run_ncat returns: '%s'" % out)
>       assert len(out) > 0
E       AssertionError: assert 0 > 0
E        +  where 0 = len('')

/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_tcp_adaptor.py:933: AssertionError
```
https://github.com/skupperproject/skupper-router/runs/6215745287?check_suite_focus=true#step:26:3048

This error started happening after ncat was added as a test dependency in this commit - https://github.com/skupperproject/skupper-router/commit/018170dc7ce7a71bac2b0d6313f1be7c305188e5

### PR DESCRIPTION
**Pull request by kgiusti**

### CODE REVIEW

File: src/adaptors/tcp_adaptor.c [hunk 1]
```diff
@@ -502,13 +502,27 @@ static void handle_disconnected(qdr_tcp_connection_t* conn)
         qd_log(tcp_adaptor->log_source, QD_LOG_DEBUG,
                "[C%"PRIu64"][L%"PRIu64"] handle_disconnected - close out_dlv_stream",
                conn->conn_id, conn->outgoing_id);
+
+        // Fun fact: the delivery pointed to by conn->initial_delivery is
+        // eventually moved to conn->out_dlv_stream.  I don't trust the code
+        // enough to be confident both pointers are not set at the same time
+        // and we risk calling remote_state_updated twice.
+        if (conn->initial_delivery == 0) {
```
Comment (ganeshmurthy) [inline src/adaptors/tcp_adaptor.c:510]: Because of the fact that `conn->initial_delivery` was set to zero in a couple of places elsewhere in the code, the need to check `conn->initial_delivery == 0` arises here. From what I can tell, there is no need to set `conn->initial_delivery` to zero since we are never reusing non-egress dispatcher connection objects. If we don't ever set the `conn->initial_delivery` to zero, then there will be no need to check if `conn->initial_delivery == 0`

Comment (kgiusti) [reply src/adaptors/tcp_adaptor.c:510]: Yeah but that's like... out of scope for this patch IMHO. Not a bad idea, but I'd hold off that change until after the release.

**Review by ganeshmurthy — APPROVED** [review]
