### PR TITLE
Fixes #680: Coverity fix - remove check for host since it is already …

### LINKED ISSUE #680: [coverity] dead_error_line: Execution cannot reach the expression `NULL` inside this statement: `record->host = (host ? qd_s....`
image

### PR DESCRIPTION
**Pull request by ganeshmurthy**
…checked previously

### CODE REVIEW

**Review by kgiusti — APPROVED** [review]
modulo clang-format warning

**Comment by ganeshmurthy** [comment]
Fixed clang-format issue

File: src/adaptors/http_common.c [hunk 1]
```diff
@@ -717,7 +717,7 @@ void qd_http_record_request(qdr_core_t *core, const char * method, uint32_t stat
     qdr_http_request_info_t* record = _new_qdr_http_request_info_t();
     record->ingress = ingress;
     record->address = address ? qd_strdup(address) : 0;
-    record->host = host ? qd_strdup(host) : 0;
+    record->host                    = qd_strdup(host);
```
Comment (jiridanek) [inline src/adaptors/http_common.c:720]: this looks like nonsensical alignment in the diff, until I realized it is aligning it with line 728 💡
